// <auto-generated />
using System;
using ACME.LearningCenterPlatform.API.Shared.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ACME.LearningCenterPlatform.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ACME.LearningCenterPlatform.API.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_amenities");

                    b.ToTable("amenities");
                });

            modelBuilder.Entity("ACME.LearningCenterPlatform.API.Profiles.Domain.Model.Aggregates.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_profiles");

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("ACME.LearningCenterPlatform.API.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("base_price");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<int>("HostId")
                        .HasColumnType("int")
                        .HasColumnName("host_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image_url");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_properties");

                    b.ToTable("properties");
                });

            modelBuilder.Entity("ACME.LearningCenterPlatform.API.PropertyAmenity", b =>
                {
                    b.Property<int>("PropertyId")
                        .HasColumnType("int")
                        .HasColumnName("property_id");

                    b.Property<int>("AmenityId")
                        .HasColumnType("int")
                        .HasColumnName("amenity_id");

                    b.HasKey("PropertyId", "AmenityId")
                        .HasName("p_k_property_amenities");

                    b.HasIndex("AmenityId")
                        .HasDatabaseName("i_x_property_amenities_amenity_id");

                    b.ToTable("property_amenities");
                });

            modelBuilder.Entity("ACME.LearningCenterPlatform.API.Publishing.Domain.Model.Aggregate.Tutorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_tutorials");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("i_x_tutorials_category_id");

                    b.ToTable("tutorials");
                });

            modelBuilder.Entity("ACME.LearningCenterPlatform.API.Publishing.Domain.Model.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("TutorialId")
                        .HasColumnType("int")
                        .HasColumnName("tutorial_id");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("asset_type")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("varchar(34)")
                        .HasColumnName("asset_type");

                    b.HasKey("Id")
                        .HasName("p_k_assets");

                    b.HasIndex("TutorialId")
                        .HasDatabaseName("i_x_assets_tutorial_id");

                    b.ToTable("assets");

                    b.HasDiscriminator<string>("asset_type").HasValue("asset_base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ACME.LearningCenterPlatform.API.Publishing.Domain.Model.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_categories");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("ACME.LearningCenterPlatform.API.Publishing.Domain.Model.Entities.ImageAsset", b =>
                {
                    b.HasBaseType("ACME.LearningCenterPlatform.API.Publishing.Domain.Model.Entities.Asset");

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image_uri");

                    b.ToTable("assets");

                    b.HasDiscriminator().HasValue("asset_image");
                });

            modelBuilder.Entity("ACME.LearningCenterPlatform.API.Publishing.Domain.Model.Entities.ReadableContentAsset", b =>
                {
                    b.HasBaseType("ACME.LearningCenterPlatform.API.Publishing.Domain.Model.Entities.Asset");

                    b.Property<string>("ReadableContent")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("readable_content");

                    b.ToTable("assets");

                    b.HasDiscriminator().HasValue("asset_readable_content");
                });

            modelBuilder.Entity("ACME.LearningCenterPlatform.API.Publishing.Domain.Model.Entities.VideoAsset", b =>
                {
                    b.HasBaseType("ACME.LearningCenterPlatform.API.Publishing.Domain.Model.Entities.Asset");

                    b.Property<string>("VideoUri")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("video_uri");

                    b.ToTable("assets");

                    b.HasDiscriminator().HasValue("asset_video");
                });

            modelBuilder.Entity("ACME.LearningCenterPlatform.API.Profiles.Domain.Model.Aggregates.Profile", b =>
                {
                    b.OwnsOne("ACME.LearningCenterPlatform.API.Profiles.Domain.Model.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("email_address");

                            b1.HasKey("Id")
                                .HasName("p_k_profiles");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_profiles_profiles_id");
                        });

                    b.OwnsOne("ACME.LearningCenterPlatform.API.Profiles.Domain.Model.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("last_name");

                            b1.HasKey("Id")
                                .HasName("p_k_profiles");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_profiles_profiles_id");
                        });

                    b.OwnsOne("ACME.LearningCenterPlatform.API.Profiles.Domain.Model.ValueObjects.StreetAddress", "Address", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address_country");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address_street");

                            b1.HasKey("Id")
                                .HasName("p_k_profiles");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_profiles_profiles_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("ACME.LearningCenterPlatform.API.PropertyAmenity", b =>
                {
                    b.HasOne("ACME.LearningCenterPlatform.API.Amenity", "Amenity")
                        .WithMany("PropertyAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_property_amenities_amenities_amenity_id");

                    b.HasOne("ACME.LearningCenterPlatform.API.Property", "Property")
                        .WithMany("PropertyAmenities")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_property_amenities_properties_property_id");

                    b.Navigation("Amenity");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("ACME.LearningCenterPlatform.API.Publishing.Domain.Model.Aggregate.Tutorial", b =>
                {
                    b.HasOne("ACME.LearningCenterPlatform.API.Publishing.Domain.Model.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_tutorials__category_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ACME.LearningCenterPlatform.API.Publishing.Domain.Model.Entities.Asset", b =>
                {
                    b.HasOne("ACME.LearningCenterPlatform.API.Publishing.Domain.Model.Aggregate.Tutorial", null)
                        .WithMany("Assets")
                        .HasForeignKey("TutorialId")
                        .HasConstraintName("f_k_assets_tutorials_tutorial_id");

                    b.OwnsOne("ACME.LearningCenterPlatform.API.Publishing.Domain.Model.Entities.AcmeAssetIdentifier", "AssetIdentifier", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<Guid>("Identifier")
                                .HasColumnType("char(36)")
                                .HasColumnName("asset_identifier");

                            b1.HasKey("Id")
                                .HasName("p_k_assets");

                            b1.ToTable("assets");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_assets__asset_id");
                        });

                    b.Navigation("AssetIdentifier")
                        .IsRequired();
                });

            modelBuilder.Entity("ACME.LearningCenterPlatform.API.Amenity", b =>
                {
                    b.Navigation("PropertyAmenities");
                });

            modelBuilder.Entity("ACME.LearningCenterPlatform.API.Property", b =>
                {
                    b.Navigation("PropertyAmenities");
                });

            modelBuilder.Entity("ACME.LearningCenterPlatform.API.Publishing.Domain.Model.Aggregate.Tutorial", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
